security:
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER ]

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        swagger_ui:
            pattern: ^/api/docs
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\KeycloakAuthenticator

    access_control:
        - { path: ^/api/docs(\.json)?$, roles: PUBLIC_ACCESS }
        - { path: ^/health$, roles: PUBLIC_ACCESS }
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/users, roles: ROLE_USER }
        - { path: ^/api, roles: ROLE_USER }
