security:
    role_hierarchy:
        ROLE_ADMIN: [ ROLE_USER ]

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Built-in JWT user provider from Lexik (no custom class)
        jwt:
            lexik_jwt: ~

        # Keep your DB user provider for later (non-JWT) use if you want
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api
            stateless: true
            provider: jwt
            jwt: ~

        swagger_ui:
            pattern: ^/api/docs
            security: false
#        main:
##            stateless: true
##            jwt: ~
#            lazy: true
#            provider: users_in_memory

    access_control:
         - { path: ^/api/admin, roles: ROLE_ADMIN }
         - { path: ^/api/users, roles: ROLE_USER }
         - { path: ^/api/docs(\.json)?$, roles: PUBLIC_ACCESS }
         - { path: ^/api, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
