monolog:
    handlers:
        main:
            type: stream
            path: "php://stdout"
            level: debug
            channels: ["!event"]
            formatter: monolog.formatter.json

        file:
            type: stream
            path: "%kernel.logs_dir%/dev.log"
            level: debug
            formatter: monolog.formatter.json

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
