blank_issues_enabled: false
contact_links:
  - name: Questions / Ideas
    url: https://github.com/marcel-tuinstra/symfony-api-starter/discussions
    about: For general questions, discussions, or suggestions.
