sentry:
    dsn: '%env(SENTRY_DSN)%'
    options:
        environment: '%kernel.environment%'
        release: '%env(APP_VERSION)%'
        traces_sample_rate: 1.0

monolog:
    handlers:
        main:
            type: rotating_file
            path: '%kernel.logs_dir%/app.log'
            level: info
            formatter: monolog.formatter.json
            max_files: 14

        sentry_logs:
            type: service
            id: Sentry\SentryBundle\Monolog\LogsHandler

    services:
        Sentry\SentryBundle\Monolog\LogsHandler:
            arguments:
                - !php/const Monolog\Logger::INFO
