controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

healthcheck:
    path: /health
    controller: App\Controller\HealthcheckController
    methods: [GET]
